const fs = require('fs');
const path = require('path');
const archiver = require('archiver');
const PDFDocument = require('pdfkit');
const logger = require('./logger');

class ExportManager {
  constructor() {
    this.screenshotCounter = 0;
  }

  // Export to ZIP
  async toZip(sourceDir, outputPath) {
    return new Promise((resolve, reject) => {
      const output = fs.createWriteStream(outputPath);
      const archive = archiver('zip', { zlib: { level: 9 } });

      output.on('close', () => {
        const size = archive.pointer();
        logger.info(`ZIP exported: ${outputPath} (${size} bytes)`);
        resolve({ path: outputPath, size });
      });

      archive.on('error', reject);
      archive.pipe(output);

      // Add all files from source directory
      const files = this.getAllFiles(sourceDir);
      for (const file of files) {
        const relativePath = path.relative(sourceDir, file);
        archive.file(file, { name: relativePath });
      }

      archive.finalize();
    });
  }

  // Generate PDF report
  async toPdf(cloneData, outputPath) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          bufferPages: true
        });

        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        // Title page
        doc.fontSize(25).text('Living Clone Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(14).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Target: ${cloneData.url || 'N/A'}`, { align: 'center' });
        doc.moveDown(2);

        // Summary section
        doc.fontSize(18).text('Summary');
        doc.moveDown();
        doc.fontSize(12).text(`Pages Cloned: ${cloneData.pagesCount || 0}`);
        doc.text(`Total Size: ${this.formatBytes(cloneData.totalSize || 0)}`);
        doc.text(`Duration: ${cloneData.duration || 'N/A'}`);
        doc.text(`Errors: ${cloneData.errors || 0}`);
        doc.moveDown(2);

        // Pages section
        doc.fontSize(18).text('Pages');
        doc.moveDown();

        if (cloneData.pages && cloneData.pages.length > 0) {
          for (const page of cloneData.pages.slice(0, 50)) {
            doc.fontSize(10).text(`• ${page.url}`);
            doc.fontSize(8).text(`  Status: ${page.status} | Size: ${this.formatBytes(page.size)}`);
            doc.moveDown(0.5);
          }
          
          if (cloneData.pages.length > 50) {
            doc.fontSize(10).text(`... and ${cloneData.pages.length - 50} more pages`);
          }
        } else {
          doc.fontSize(10).text('No pages data available');
        }

        doc.moveDown(2);

        // Network activity section
        if (cloneData.networkLog && cloneData.networkLog.length > 0) {
          doc.addPage();
          doc.fontSize(18).text('Network Activity');
          doc.moveDown();

          for (const entry of cloneData.networkLog.slice(0, 100)) {
            doc.fontSize(8).text(`${entry.timestamp?.toLocaleTimeString() || 'N/A'} | ${entry.type} | ${entry.url}`);
          }
        }

        // Errors section
        if (cloneData.errors && cloneData.errors.length > 0) {
          doc.addPage();
          doc.fontSize(18).text('Errors');
          doc.moveDown();

          for (const error of cloneData.errors) {
            doc.fontSize(10).text(`• ${error.message || error}`);
            if (error.url) {
              doc.fontSize(8).text(`  URL: ${error.url}`);
            }
            doc.moveDown(0.5);
          }
        }

        // Footer
        doc.fontSize(8).text('Generated by Living Clone - XSS Testing Tool', { align: 'center' });

        doc.end();

        stream.on('finish', () => {
          const stats = fs.statSync(outputPath);
          logger.info(`PDF exported: ${outputPath} (${stats.size} bytes)`);
          resolve({ path: outputPath, size: stats.size });
        });

      } catch (error) {
        reject(error);
      }
    });
  }

  // Take screenshot (requires puppeteer)
  async screenshot(url, outputPath, options = {}) {
    let puppeteer;
    try {
      puppeteer = require('puppeteer');
    } catch (e) {
      logger.warn('Puppeteer not installed. Screenshot feature unavailable.');
      return null;
    }

    let browser;
    try {
      browser = await puppeteer.launch({
        headless: 'new',
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });

      const page = await browser.newPage();
      
      await page.setViewport({
        width: options.width || 1920,
        height: options.height || 1080
      });

      await page.goto(url, {
        waitUntil: options.waitUntil || 'networkidle0',
        timeout: options.timeout || 30000
      });

      await page.screenshot({
        path: outputPath,
        fullPage: options.fullPage || false,
        type: options.type || 'png'
      });

      const stats = fs.statSync(outputPath);
      logger.info(`Screenshot saved: ${outputPath} (${stats.size} bytes)`);
      
      return { path: outputPath, size: stats.size };
    } catch (error) {
      logger.error('Screenshot failed', { error: error.message });
      return null;
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  // Take multiple screenshots
  async screenshots(urls, outputDir, options = {}) {
    const results = [];
    
    for (const url of urls) {
      this.screenshotCounter++;
      const filename = `screenshot-${this.screenshotCounter}.png`;
      const outputPath = path.join(outputDir, filename);
      
      const result = await this.screenshot(url, outputPath, options);
      if (result) {
        results.push({ url, ...result });
      }
    }

    return results;
  }

  // Generate HTML report
  toHtml(cloneData, outputPath) {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Living Clone Report - ${cloneData.url || 'Unknown'}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #1a1a2e; color: #eaeaea; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { text-align: center; padding: 40px 0; border-bottom: 2px solid #16213e; margin-bottom: 30px; }
        .header h1 { font-size: 2.5em; color: #0f3460; margin-bottom: 10px; }
        .header .subtitle { color: #888; font-size: 1.1em; }
        .card { background: #16213e; border-radius: 10px; padding: 25px; margin-bottom: 20px; box-shadow: 0 4px 15px rgba(0,0,0,0.3); }
        .card h2 { color: #e94560; margin-bottom: 15px; font-size: 1.5em; }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; }
        .stat-box { background: #0f3460; padding: 20px; border-radius: 8px; text-align: center; }
        .stat-box .value { font-size: 2em; color: #e94560; font-weight: bold; }
        .stat-box .label { color: #888; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #0f3460; }
        th { background: #0f3460; color: #e94560; }
        tr:hover { background: #1a1a3e; }
        .status { padding: 4px 8px; border-radius: 4px; font-size: 0.9em; }
        .status-2xx { background: #2ecc71; color: #000; }
        .status-3xx { background: #f39c12; color: #000; }
        .status-4xx { background: #e74c3c; color: #fff; }
        .status-5xx { background: #8e44ad; color: #fff; }
        .error { background: #2c0b0e; border-left: 4px solid #e94560; padding: 15px; margin: 10px 0; border-radius: 4px; }
        .error-message { color: #e94560; font-weight: bold; }
        .error-url { color: #888; font-size: 0.9em; margin-top: 5px; }
        .footer { text-align: center; padding: 30px 0; color: #666; border-top: 1px solid #16213e; margin-top: 30px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Living Clone Report</h1>
            <div class="subtitle">Generated: ${new Date().toLocaleString()}</div>
            <div class="subtitle">Target: ${cloneData.url || 'N/A'}</div>
        </div>

        <div class="card">
            <h2>Summary</h2>
            <div class="stats">
                <div class="stat-box">
                    <div class="value">${cloneData.pagesCount || 0}</div>
                    <div class="label">Pages Cloned</div>
                </div>
                <div class="stat-box">
                    <div class="value">${this.formatBytes(cloneData.totalSize || 0)}</div>
                    <div class="label">Total Size</div>
                </div>
                <div class="stat-box">
                    <div class="value">${cloneData.duration || 'N/A'}</div>
                    <div class="label">Duration</div>
                </div>
                <div class="stat-box">
                    <div class="value">${cloneData.errors || 0}</div>
                    <div class="label">Errors</div>
                </div>
            </div>
        </div>

        <div class="card">
            <h2>Pages</h2>
            <table>
                <thead>
                    <tr>
                        <th>URL</th>
                        <th>Status</th>
                        <th>Size</th>
                        <th>Depth</th>
                    </tr>
                </thead>
                <tbody>
                    ${(cloneData.pages || []).map(page => `
                        <tr>
                            <td>${page.url}</td>
                            <td><span class="status status-${Math.floor(page.status / 100)}xx">${page.status}</span></td>
                            <td>${this.formatBytes(page.size)}</td>
                            <td>${page.depth || 0}</td>
                        </tr>
                    `).join('')}
                </tbody>
            </table>
        </div>

        ${cloneData.errors && cloneData.errors.length > 0 ? `
        <div class="card">
            <h2>Errors</h2>
            ${cloneData.errors.map(error => `
                <div class="error">
                    <div class="error-message">${error.message || error}</div>
                    ${error.url ? `<div class="error-url">${error.url}</div>` : ''}
                </div>
            `).join('')}
        </div>
        ` : ''}

        <div class="footer">
            Generated by Living Clone - XSS Testing Tool
        </div>
    </div>
</body>
</html>`;

    fs.writeFileSync(outputPath, html, 'utf8');
    const stats = fs.statSync(outputPath);
    logger.info(`HTML report exported: ${outputPath} (${stats.size} bytes)`);
    
    return { path: outputPath, size: stats.size };
  }

  // Generate JSON report
  toJson(cloneData, outputPath) {
    const report = {
      generated: new Date().toISOString(),
      tool: 'Living Clone v2.0.0',
      ...cloneData
    };

    fs.writeFileSync(outputPath, JSON.stringify(report, null, 2), 'utf8');
    const stats = fs.statSync(outputPath);
    logger.info(`JSON report exported: ${outputPath} (${stats.size} bytes)`);
    
    return { path: outputPath, size: stats.size };
  }

  // Generate diff between two clones
  diff(clone1, clone2, outputPath) {
    const diff = {
      generated: new Date().toISOString(),
      clone1: {
        url: clone1.url,
        pages: clone1.pagesCount,
        size: clone1.totalSize
      },
      clone2: {
        url: clone2.url,
        pages: clone2.pagesCount,
        size: clone2.totalSize
      },
      differences: {
        pagesAdded: [],
        pagesRemoved: [],
        pagesChanged: [],
        sizeDifference: (clone2.totalSize || 0) - (clone1.totalSize || 0)
      }
    };

    // Compare pages
    const urls1 = new Set((clone1.pages || []).map(p => p.url));
    const urls2 = new Set((clone2.pages || []).map(p => p.url));

    for (const url of urls2) {
      if (!urls1.has(url)) {
        diff.differences.pagesAdded.push(url);
      }
    }

    for (const url of urls1) {
      if (!urls2.has(url)) {
        diff.differences.pagesRemoved.push(url);
      }
    }

    // Compare changed pages
    for (const page1 of (clone1.pages || [])) {
      const page2 = (clone2.pages || []).find(p => p.url === page1.url);
      if (page2 && page1.size !== page2.size) {
        diff.differences.pagesChanged.push({
          url: page1.url,
          oldSize: page1.size,
          newSize: page2.size
        });
      }
    }

    fs.writeFileSync(outputPath, JSON.stringify(diff, null, 2), 'utf8');
    const stats = fs.statSync(outputPath);
    logger.info(`Diff report exported: ${outputPath}`);
    
    return { path: outputPath, size: stats.size };
  }

  // Helper methods
  getAllFiles(dirPath) {
    const files = [];
    const items = fs.readdirSync(dirPath);
    
    for (const item of items) {
      const fullPath = path.join(dirPath, item);
      const stat = fs.statSync(fullPath);
      
      if (stat.isDirectory()) {
        files.push(...this.getAllFiles(fullPath));
      } else {
        files.push(fullPath);
      }
    }
    
    return files;
  }

  formatBytes(bytes) {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }
}

module.exports = new ExportManager();
